name: buildx

on:
  push:
    branches: master
    tags: v.*

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prepare
        run: |
          case $GITHUB_REF in
          refs/tags/*)
              echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}
              ;;
          refs/heads/master)
              echo ::set-output name=tag::latest
              ;;
          refs/heads/*)
              echo ::set-output name=tag::${GITHUB_REF#refs/heads/}
              ;;
          *)
              echo ::set-output name=tag::snapshot
          esac

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup up docker buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1.2.1
        with:
          version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Docker login
        if: success()
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login --username "${{ secrets.DOCKER_USERNAME }}" \
            --password "${DOCKER_PASSWORD}"

      - name: Run buildx
        run: |
          docker buildx build \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x \
            --output type=image,push=true \
            --tag "${{ secrets.DOCKER_USERNAME }}/scapy:${{ steps.prepare.outputs.tag }}" \
            --file Dockerfile .

      - name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
